# Generated by Django 3.2.6 on 2021-08-24 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='towhid_post',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='towhid_post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
