# Generated by Django 3.2.6 on 2021-11-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hajj_posts_swalah_posts_swaum_posts_zakat_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouresalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
