# Generated by Django 3.2.6 on 2021-11-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211130_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='couresalimage',
            name='image',
            field=models.ImageField(blank=True, unique=True, upload_to=''),
        ),
    ]
