# Generated by Django 3.2.6 on 2021-12-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_article_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couresalimage',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='couresalimage',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
